# Mikrofon/Högtalare
audio:
  input_device: null          # index eller null för default
  sample_rate: 16000
  channels: 1
  chunk_ms: 30
  vad:
    enabled: true
    aggressiveness: 2         # 0–3

# STT (Speech-to-Text)
stt:
  mode: local                 # "local" för lokal Whisper-transkribering, "upload" för att skicka ljud till n8n
  language: sv
  piper:
    model: base               # tiny, base, small, medium, large (större = bättre kvalitet men långsammare)
    device: cpu               # cpu eller cuda

# TTS (lokalt Piper)
tts:
  piper:
    model_path: models/piper/sv-SE_piper.onnx
    config_path: models/piper/sv-SE_piper.onnx.json
    output_wav: /tmp/tts_out.wav
    playback_cmd: ["aplay", "-q", "/tmp/tts_out.wav"]

# Central endpoint (n8n webhook)
backend:
  n8n_url: "https://ai.genio-bot.com/webhook/text-input"     # för textfrågor
  audio_url: "https://ai.genio-bot.com/webhook/audio-input"  # för ljuduppladdning (om mode: upload)
  response_key: reply
  timeout_s: 30
  headers: {}

logging:
  level: INFO
