# Exempelkonfiguration för den nya Genio Bot-appen.
# Kopiera denna fil till config.yaml och kör sedan `python -m src.app`.

n8n:
  server_url: "https://ai.genio-bot.com"
  text_webhook_path: "/webhook/genio-bot-question"
  response_webhook_path: "/webhook/genio-bot-response"

app:
  public_base_url: "https://ai.genio-bot.com"
  reply_webhook_path: "/api/v1/webhooks/genio-bot-reply"
  listen_host: "0.0.0.0"
  listen_port: 8010
  reply_timeout_s: 45

stt:
  model_size: "small"
  language: "sv"
  device: "cpu"
  compute_type: "int8"

tts:
  model_path: "./piper/models/sv-se_nst-medium.onnx"
  config_path: "./piper/models/sv-se_nst-medium.onnx.json"
  output_wav: "/tmp/genio-bot-tts.wav"
  playback_cmd:
    - "aplay"
    - "-q"
    - "/tmp/genio-bot-tts.wav"
