version: "3.8"

# This docker-compose file runs ONLY the Wyoming STT server
# Use this if you want to run the satellite application manually (not in Docker)

services:
  wyoming-whisper:
    image: rhasspy/wyoming-faster-whisper:latest
    ports:
      - "10300:10300"
    volumes:
      - whisper-data:/data
    command: --model base --language sv
    restart: unless-stopped

volumes:
  whisper-data:
