version: "3.8"
services:
  # Satellite client (this application)
  # No longer requires separate STT server - runs locally or uploads to n8n
  satellite:
    build: .
    devices:
      - "/dev/snd:/dev/snd"
    volumes:
      - ./:/app
      - whisper-models:/root/.cache/huggingface  # Cache for Whisper models
    environment:
      - PYTHONUNBUFFERED=1
    command: ["python", "src/main.py", "--config", "config.docker.yaml"]
    restart: unless-stopped

volumes:
  whisper-models:
